# Welcome to Numpy

In [1]:
import numpy as np

In [2]:
myarr = np.array([[1,2,3,4,5],[2,4,6,8,0]])

In [3]:
myarr

array([[1, 2, 3, 4, 5],
       [2, 4, 6, 8, 0]])

In [4]:
myarr.shape

(2, 5)

In [5]:
myarr.dtype

dtype('int32')

In [6]:
myarr[0,1] = 45

In [7]:
myarr

array([[ 1, 45,  3,  4,  5],
       [ 2,  4,  6,  8,  0]])

# Array Creration: Conversion from other python structure

In [8]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [9]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
array.dtype

dtype('int32')

In [11]:
array.shape

(3, 3)

In [12]:
array.size

9

# Create numpy Array by some functions

In [13]:
zero = np.zeros((2,5))

In [14]:
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
zero.shape

(2, 5)

In [16]:
zero.size

10

In [17]:
arng = np.arange(10)

In [18]:
arng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
lspace = np.linspace(1,50,10)

In [20]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [21]:
emp = np.empty((2,5))

In [22]:
emp

array([[ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778],
       [28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ]])

In [23]:
emp_like = np.empty_like(lspace)

In [24]:
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [25]:
ide = np.identity(4)

In [26]:
ide

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

*Create an array by arange method*

In [27]:
arr = np.arange(60)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

*Convert 1D to 2D array*

In [29]:
arr=arr.reshape(12,5)

In [30]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [31]:
arr.shape

(12, 5)

In [32]:
arr = arr.ravel()

In [33]:
arr.shape

(60,)

In [34]:
x=[[1,2,3],[4,5,6],[7,8,9]]

In [35]:
arr1 = np.array(x)

In [36]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
arr1.sum()

45

*Axis=0 means rows it is sum of rows*

In [38]:
arr1.sum(axis=0)

array([12, 15, 18])

*Axis=0 means columns it is sum of columns*

In [39]:
arr1.sum(axis=1)

array([ 6, 15, 24])

In [40]:
arr1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [41]:
for item in arr1.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [42]:
arr1.ndim

2

In [43]:
arr1.size

9

In [44]:
arr1.shape

(3, 3)

In [45]:
arr1.argmax()

8

In [46]:
arr1.argmin()

0

In [47]:
arr1.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [48]:
arr1.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [49]:
arr1.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [50]:
arr1.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [51]:
arr1.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [52]:
arr2 = np.array([[1, 3, 5],
       [7, 9, 11],
       [13, 15, 17]])

# Perform Airthematic operation on Numpy Array

In [53]:
arr2

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [54]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
arr1+arr2

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

In [56]:
arr1*arr2

array([[  1,   6,  15],
       [ 28,  45,  66],
       [ 91, 120, 153]])

In [57]:
arr2-arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

*Multiplication of Matrix*

In [58]:
arr1@arr2

array([[ 54,  66,  78],
       [117, 147, 177],
       [180, 228, 276]])

In [81]:
ide1 = np.identity(3)

In [83]:
ide2 = np.identity(3)

**Airthematic operation on the Identy matrix**

In [84]:
ide1+ide2

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

In [85]:
ide1-ide2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [86]:
ide1@ide2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [88]:
(2*ide1)/4

array([[0.5, 0. , 0. ],
       [0. , 0.5, 0. ],
       [0. , 0. , 0.5]])

In [59]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [60]:
np.sqrt(arr2)

array([[1.        , 1.73205081, 2.23606798],
       [2.64575131, 3.        , 3.31662479],
       [3.60555128, 3.87298335, 4.12310563]])

In [61]:
arr2.max()

17

In [62]:
arr2.min()

1

In [63]:
np.where(arr1>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [64]:
np.count_nonzero(arr1)

9

In [65]:
np.nonzero(arr1)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [66]:
import sys

In [67]:
py_ar = [1,2,3,4,5]

In [68]:
np_ar = np.array(py_ar)

In [69]:
sys.getsizeof(1)*len(py_ar)

140

In [70]:
np_ar.itemsize*np_ar.size

20

In [71]:
np_ar

array([1, 2, 3, 4, 5])